from pathlib import Path
configfile: "config.yaml"
output_dir = Path(config["pipeline_output"])

rule all:
    input:
        output_dir / "data",
        output_dir / "pangenome_variations",
        output_dir / "subsampler",
        output_dir / "pandora_workflow",
        output_dir / "variant_callers_pipeline",
        output_dir / "pandora_paper_roc",
        output_dir / "pandora_gene_distance",


rule link_input_data:
    input:
        config["input_data_folder"]
    output:
        directory(output_dir / "data")
    threads: 1
    resources:
        mem_mb=100
    shell:
        "ln -s {input} {output}"
localrules: link_input_data


rule install_pangenome_variations:
    output:
          directory(output_dir / "pangenome_variations")
    threads: 1
    resources:
        mem_mb=16000
    shell:
        """
        cd {output_dir} && \
        git clone --recursive https://github.com/iqbal-lab-org/pangenome_variations && \
        cd pangenome_variations && \
        git checkout adding_strand_info && \
        ./setup.sh
        """


rule install_subsampler:
    output:
          directory(output_dir / "subsampler")
    threads: 1
    resources:
        mem_mb=16000
    shell:
        """
        cd {output_dir} && \
        git clone --recursive https://github.com/iqbal-lab-org/subsampler && \
        cd subsampler && \
        git checkout pandora_paper_update_31_03_2021 && \
        ./setup.sh
        """


rule install_pandora_workflow:
    output:
          directory(output_dir / "pandora_workflow")
    threads: 1
    resources:
        mem_mb=16000
    shell:
        """
        cd {output_dir} && \
        git clone --recursive https://github.com/iqbal-lab-org/pandora_workflow && \
        cd pandora_workflow && \
        git checkout pandora_paper_update_31_03_2021 && \
        ./setup.sh
        """


rule install_variant_callers_pipeline:
    output:
          directory(output_dir / "variant_callers_pipeline")
    threads: 1
    resources:
        mem_mb=16000
    shell:
        """
        cd {output_dir} && \
        git clone --recursive https://github.com/iqbal-lab-org/variant_callers_pipeline && \
        cd variant_callers_pipeline && \
        git checkout pandora_paper_update_31_03_2021 && \
        ./setup.sh
        """


rule install_pandora_paper_roc:
    output:
          directory(output_dir / "pandora_paper_roc")
    threads: 1
    resources:
        mem_mb=16000
    shell:
        """
        cd {output_dir} && \
        git clone --recursive https://github.com/iqbal-lab-org/pandora_paper_roc && \
        cd pandora_paper_roc && \
        git checkout adding_strand_info && \
        ./setup.sh
        """



rule install_pandora_gene_distance:
    output:
          directory(output_dir / "pandora_gene_distance")
    threads: 1
    resources:
        mem_mb=16000
    shell:
        """
        cd {output_dir} && \
        git clone --recursive https://github.com/iqbal-lab-org/pandora_gene_distance && \
        cd pandora_gene_distance && \
        git checkout pandora_paper_update_31_03_2021 && \
        ./setup.sh
        """
