cp ../pandora1_paper_analysis_output_20_way/illumina_analysis/gene_distance_plots/pandora_illumina_100x_withdenovo/gene_sample_ref_ED_nbsamples_zam.csv gene_sample_ref_ED_nbsamples.illumina.csv
cp ../pandora1_paper_analysis_output_20_way/nanopore_analysis/gene_distance_plots/pandora_nanopore_100x_withdenovo/gene_sample_ref_ED_nbsamples_zam.csv gene_sample_ref_ED_nbsamples.nanopore.csv
